---
title: "lab report knapsack"
author: "Group10"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(LAB6C)
```

##1.1.2 Brute force search

*Question: How much time does it takes to run the algorithm for n = 16 objects?*

```{r, eval=FALSE}
system.time(
  knapsack(x=knapsack_objects[1:16,], W=3500)$brute_force_knapsack()
)

# example
#    user  system elapsed 
#    0.24    0.03    0.26
```

##1.1.3 Dynamic programming

*Question How much time does it takes to run the algorithm for n = 500 objects?*

```{r, eval=FALSE}
system.time(
  knapsack(x=knapsack_objects[1:500,], W=3500)$knapsack_dynamic()
)

# example
#    user  system elapsed 
#    9.28    0.05    9.34
```

##1.1.4 Greedy heuristic

*Question How much time does it takes to run the algorithm for n = 1000000 objects?*

```{r eval=FALSE}
set.seed(42)
n <- 1000000
example <-
data.frame(
w=sample(1:4000, size = n, replace = TRUE),
v=runif(n = n, 0, 10000)
)
system.time(
  knapsack(x=example, W=3500)$greedy_knapsack()
)

# example
#    user  system elapsed 
#    0.38    0.03    0.41
```

##1.1.6 Profile your code and optimize your code




